advanced:
  async_timeout: 30
  max_concurrent_requests: 10
  retry_attempts: 3
  retry_delay: 1
auth:
  auto_login: false
  remember_user: true
  session_timeout: 3600
central_server:
  discovery_interval: 300
  enabled: true
  register_on_startup: false
  url: https://central.locrit.com
firebase:
  api_key: ''
  auth_domain: ''
  database_url: ''
  project_id: ''
  storage_bucket: ''
locrits:
  default_settings:
    access_to:
      full_memory: false
      llm_info: true
      logs: true
      quick_memory: true
    memory_service: plaintext_file
    open_to:
      humans: true
      internet: false
      invitations: true
      locrits: true
      platform: false
  instances:
    Bob Technique:
      access_to:
        full_memory: true
        llm_info: true
        logs: true
        quick_memory: true
      active: true
      created_at: '2025-09-13T14:29:07.098618'
      description: Expert en programmation et technologies
      memory_service: plaintext_file
      ollama_model: llama3.1:8b-instruct-q3_K_M
      ollama_url: http://localhost:11434
      open_to:
        humans: true
        internet: true
        invitations: true
        locrits: true
        platform: false
      public_address: https://fb73aa2142137f.lhr.life
      public_page:
        avatar: 🤖
        description: Expert en programmation et technologies. Posez-moi vos questions
          techniques !
        show_model_info: true
        theme: default
        title: Parlez avec Bob Technique
        welcome_message: Bonjour ! Je suis Bob, un expert technique. Comment puis-je
          vous aider aujourd'hui ?
      updated_at: '2025-10-05T14:29:55.066197+00:00'
    Locrit root:
      access_to:
        full_memory: true
        llm_info: true
        logs: true
        quick_memory: true
      active: false
      created_at: '2025-09-14T18:57:16.743340'
      description: Le premire locrit !
      memory_service: plaintext_file
      ollama_model: llama3.1:8b-instruct-q3_K_M
      ollama_url: http://localhost:11434
      open_to:
        humans: true
        internet: false
        invitations: true
        locrits: true
        platform: false
      public_address: ''
      updated_at: '2025-10-05T10:25:55.500933+00:00'
    Marie Recherche:
      access_to:
        full_memory: true
        llm_info: true
        logs: true
        quick_memory: true
      active: false
      created_at: '2025-09-13T14:29:07.098617'
      description: Spécialisée dans la recherche et l'analyse
      memory_service: plaintext_file
      ollama_model: llama3.1:8b-instruct-q3_K_M
      ollama_url: http://localhost:11434
      open_to:
        humans: true
        internet: true
        invitations: true
        locrits: true
        platform: false
      public_address: marie.example.com
    Pixie Assistant:
      access_to:
        full_memory: false
        llm_info: true
        logs: true
        quick_memory: true
      active: true
      created_at: '2025-09-13T14:29:07.098610'
      description: Assistant personnel intelligent et organisé
      memory_service: plaintext_file
      ollama_model: llama3.1:8b-instruct-q3_K_M
      ollama_url: http://localhost:11434
      open_to:
        humans: true
        internet: false
        invitations: true
        locrits: true
        platform: false
      public_address: pixie.localhost.run
logging:
  backup_count: 5
  console_output: true
  file_path: logs/locrit.log
  level: INFO
  max_file_size: 10MB
memory:
  database_path: data/locrit_memory.db
  embedding_model: nomic-embed-text
  enabled: false
  max_messages: 10000
  use_kuzu: false
  vector_index_path: data/vector_index.faiss
network:
  api_server:
    auto_start: false
    host: 0.0.0.0
    port: 8000
  tunnel:
    auto_start: false
    custom_subdomain: ''
    enabled: false
    provider: localhost.run
ollama:
  base_url: http://localhost:11434
  default_model: llama3.1:8b-instruct-q3_K_M
  host: localhost
  port: 11434
  timeout: 30
search:
  max_results: 10
  provider: duckduckgo
  safe_search: moderate
ui:
  auto_refresh: true
  max_log_lines: 1000
  refresh_interval: 5
  show_timestamps: true
  theme: dark
